export const DEVICE_CHANGED = 'DEVICE_CHANGED'
export const GOT_DEVICES = 'GOT_DEVICES'
export const CONNECT = 'CONNECT'
export const DISCONNECT = 'DISCONNECT'
export const CONNECTED = 'CONNECTED'
export const FAILED_TO_CONNECT = 'FAILED_TO_CONNECT'
export const DISCONNECTED = 'DISCONNECTED'
export const REFRESH_DEVICES = 'REFRESH_DEVICES'
export const TOGGLE_CONNECTION = 'TOGGLE_CONNECTION'
export const DATA_PARSED = 'DATA_PARSED'

export const TAB_SELECTED = 'TAB_SELECTED'

export const GRAPH_FILTERED = 'GRAPH_FILTERED'
